### ISSUE TITLE
Get all values from a nested array

### ISSUE THREAD

**Issue by ecdeveloper** [wilmoore/selectn#13]
Hey,

It would be really great if I could get a range of values from a nested array. So assume I have an object which looks like this:
```
{
    prop1: {
        prop2: [
            { prop3: 'abc' },
            { prop3: 'def' }
        ]
    }
}
```

I can get them now by calling:
```
selectn('prop1.prop2[0].prop3', obj);
selectn('prop1.prop2[1].prop3', obj);
```
But it would be handy to use something like: 
```
selectn('prop1.prop2[].prop3', obj);
or
selectn('prop1.prop2[*].prop3', obj);
```

Is that doable somehow?

Thanks

**Comment by wilmoore** [comment]
> Is that doable somehow?

Yes, this is doable. I wrote up a prototype and while it works, I wasn't satisfied with the potential for edge cases. For example:

```
var data = {
  people: [
    { name: '', age: 27 },
    { name: '', age: 35 },
    { name: '', age: 18 },
    { name: '', age: 21 }
  ]
};
```

If we use the proposed syntax, it would be something like:

```
selectn("people[*].age")
//=> [ 27, 35, 18, 21 ]
```

This works fine; however, things start to get weird with the following structure:

```
var data = {
  people: [
    { name: '', about: { age: 27 } },
    { name: '', about: { age: 35 } },
    { name: '', about: { age: 18 } },
    { name: '', about: { age: 21 } }
  ]
};
```

One would expect the following to work:

```
selectn("people[*].about.age")
//=> undefined
```

The problem is that instead of plucking `about.age` we are actually saying, pluck `about`, then get the `age` index from the resulting array.

One way to correct this is to ensure that anytime we see the special `*`, we concatenate the rest of the path elements and do a deep pluck (i.e. in the above above, this would be `about.age`). This would absolutely work; however, when you consider we've increased the LOC by almost 1/3 and added to the scope of the module by special casing the `*` manipulating the path, I have to think, it isn't worth it.

Besides, it's quite compose-able as-is if you consider the following example:

```
var data = {
  people: [
    { name: '', about: { age: 27 } },
    { name: '', about: { age: 35 } },
    { name: '', about: { age: 18 } },
    { name: '', about: { age: 21 } }
  ]
};

var ages = selectn("people", data).map(selectn("about.age"));
//=> [ 27, 35, 18, 21 ]
```

or if you know for sure `data.people` exists:

```
var ages = data.people.map(selectn("about.age"));
//=> [ 27, 35, 18, 21 ]
```

If not in an ES5 environment, you can use a shim for `.map` or you can use the underscore or lodash libs.

**Comment by mavarazy** [comment]
Wonder if you reconsider fixing this since selectn is used in https://github.com/CacheControl/json-rules-engine

We have following use case
```js
let obj = {
    medications: [
      { type: "A" },
      { type: "B" },
      { type: "C" }
    ]
  };
```
And we need an event triggered if type is one of "A", "C", but
```js
selectn("medications.type", obj)
```
would return `undefined` instead of an array of `A, B, C`

**Comment by wilmoore** [comment]
@mavarazy - Given you are expecting a list (array) back, you might be looking for this instead: https://www.npmjs.com/package/array-mapcat

**Comment by wilmoore** [comment]
@mavarazy Definitely let me know if that does or doesn't work for you or if we need to figure out some other solution.

**Comment by mavarazy** [comment]
Thanks. I worked around that.
